### ISSUE TITLE
hi,how to use it

### ISSUE THREAD

**Issue by Bilibilizm** [meatbroc/geofs-atc-airspace#1]

**Comment by meatbroc2** [comment]
open console by pressing ctrl+shift+j, then paste the contents of user.js into the console.
a button labeled "AIRSPACE" will appear at the top and pressing it will display a VIS and RDR button.
both modes will alert you when players enter the vicinity of PHNL airport
more functionality, such as airport changes, is coming soon

**Comment by Bilibilizm** [comment]
> open console by pressing ctrl+shift+j, then paste the contents of user.js into the console. a button labeled "AIRSPACE" will appear at the top and pressing it will display a VIS and RDR button. both modes will alert you when players enter the vicinity of PHNL airport more functionality, such as airport changes, is coming soon

How to use VIS and RDR?

**Comment by meatbroc** [comment]
Selecting RDR will open a radius incrementer where you can increase & decrease the radius of your airspace. Then, you'll enter the ICAO code of the airport into the airport menu & press the arrow to the right. If the text turns green, your airspace is being monitored for changes. If it turns red, the ICAO is invalid. Selecting VIS will automatically monitor which players are visible to you and notify you of changes.

**Comment by Bilibilizm** [comment]
Ok thanks
